<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('ARC_DOCUMENTS', function (Blueprint $table) {
            $table->string('DOC_NUMERO', 10);
            $table->string('DOC_PIECE', 30)->nullable();
            $table->string('DOC_PIECE2', 60)->nullable();
            $table->string('DOC_RPIECE', 30)->nullable();
            $table->string('DOC_TYPE', 1)->nullable();
            $table->string('DOC_STYPE', 1)->nullable();
            $table->string('DOC_ETAT', 1)->nullable();
            $table->dateTime('DOC_DATE')->nullable();
            $table->dateTime('DOC_DT_PRV')->nullable();
            $table->dateTime('DOC_DTINV')->nullable();
            $table->string('DOC_TPINV', 1)->nullable();
            $table->boolean('DOC_EN_TTC')->nullable();
            $table->string('DOC_REFPCF', 100)->nullable();
            $table->boolean('DOC_FACTRA')->nullable();
            $table->text('DOC_MEMO')->nullable();
            $table->string('PCF_CODE', 20)->nullable();
            $table->string('PCF_PAYEUR', 20)->nullable()->index('adc_kpyeur');
            $table->decimal('PCF_REMVAL', 8, 3)->nullable();
            $table->decimal('PCF_REMMIN', 20, 4)->nullable();
            $table->string('CCT_NUMERO', 10)->nullable();
            $table->string('DOC_F_TITL', 60)->nullable();
            $table->string('DOC_F_RS', 60)->nullable();
            $table->string('DOC_F_RS2', 60)->nullable();
            $table->string('DOC_F_RUE', 60)->nullable();
            $table->string('DOC_F_COMP', 60)->nullable();
            $table->string('DOC_F_ETAT', 100)->nullable();
            $table->string('DOC_F_REG', 100)->nullable();
            $table->string('DOC_F_CP', 10)->nullable();
            $table->string('DOC_F_VILL', 200)->nullable();
            $table->string('PAY_CODE', 3)->nullable();
            $table->string('DOC_F_CBAR', 30)->nullable();
            $table->string('DOC_F_SIRET', 14)->nullable();
            $table->text('DOC_F_MEMO')->nullable();
            $table->string('DOC_PCFLIV', 20)->nullable();
            $table->boolean('DOC_FPYEUR')->nullable();
            $table->boolean('DOC_LIVCLI')->nullable();
            $table->string('DOC_L_TITL', 60)->nullable();
            $table->string('DOC_L_RS', 60)->nullable();
            $table->string('DOC_L_RS2', 60)->nullable();
            $table->string('DOC_L_RUE', 60)->nullable();
            $table->string('DOC_L_COMP', 60)->nullable();
            $table->string('DOC_L_ETAT', 100)->nullable();
            $table->string('DOC_L_REG', 100)->nullable();
            $table->string('DOC_L_CP', 10)->nullable();
            $table->string('DOC_L_VILL', 200)->nullable();
            $table->string('DOC_L_PAYS', 3)->nullable();
            $table->string('DOC_L_CBAR', 30)->nullable();
            $table->string('DOC_L_SIRET', 14)->nullable();
            $table->text('DOC_L_MEMO')->nullable();
            $table->string('DOC_ORIGIN', 15)->nullable();
            $table->string('DOC_REFUS', 15)->nullable();
            $table->string('TRP_CODE', 3)->nullable();
            $table->string('TAR_CODE', 30)->nullable();
            $table->string('DEV_CODE', 3)->nullable();
            $table->string('DOC_LANGUE', 15)->nullable();
            $table->string('REG_CODE', 8)->nullable();
            $table->string('NAT_CODE', 3)->nullable();
            $table->string('SRV_CODE', 3)->nullable();
            $table->string('DIV_CODE', 3)->nullable();
            $table->string('REP_CODE', 3)->nullable();
            $table->string('SAL_CODE', 3)->nullable();
            $table->string('DEP_CODE', 3)->nullable();
            $table->string('DOC_TDEPOT', 3)->nullable();
            $table->string('PRJ_CODE', 40)->nullable();
            $table->dateTime('DOC_EDIDLC')->nullable();
            $table->string('DOC_EDICOT', 35)->nullable();
            $table->string('DOC_REFEDI', 35)->nullable();
            $table->string('DOC_EDICTR', 35)->nullable();
            $table->string('DOC_EDINDC', 35)->nullable();
            $table->boolean('DOC_CCEDIX')->nullable();
            $table->boolean('DOC_FEDIX')->nullable();
            $table->string('DOC_CBARSU', 30)->nullable();
            $table->string('DOC_CBAREMET', 30)->nullable();
            $table->dateTime('DOC_DEIOPS')->nullable();
            $table->string('DOC_NIIOPS', 35)->nullable();
            $table->string('DOC_NMIOPS', 14)->nullable();
            $table->string('DOC_CEIOPS', 13)->nullable();
            $table->string('DOC_NCIOPS', 35)->nullable();
            $table->dateTime('DOC_DCIOPS')->nullable();
            $table->string('DOC_SLIOPS', 35)->nullable();
            $table->string('DOC_CFIOPS', 13)->nullable();
            $table->string('DOC_TCIOPS', 80)->nullable();
            $table->string('DOC_TLIOPS', 80)->nullable();
            $table->dateTime('DOC_DEIOPH')->nullable();
            $table->string('DOC_NIIOPH', 35)->nullable();
            $table->string('DOC_NMIOPH', 14)->nullable();
            $table->string('DOC_CEIOPH', 13)->nullable();
            $table->string('DOC_NCIOPH', 35)->nullable();
            $table->dateTime('DOC_DCIOPH')->nullable();
            $table->string('DOC_SLIOPH', 35)->nullable();
            $table->string('DOC_CFIOPH', 13)->nullable();
            $table->string('DOC_NMIOEF', 14)->nullable();
            $table->string('DOC_REFOXT', 35)->nullable();
            $table->boolean('DOC_CHORUS')->nullable();
            $table->dateTime('DOC_CHOLE')->nullable();
            $table->string('DOC_CHOPAR', 20)->nullable();
            $table->string('DOC_CSCHRS', 100)->nullable();
            $table->string('DOC_NMCHRS', 50)->nullable();
            $table->string('DOC_NECHRS', 50)->nullable();
            $table->string('DOC_NCCHRS', 50)->nullable();
            $table->integer('DOC_CONTRME')->nullable();
            $table->float('DOC_TX_DEV', 53, 0)->nullable();
            $table->decimal('DOC_HAUSSE', 8, 3)->nullable();
            $table->string('DEB_NATURE', 2)->nullable();
            $table->string('DEB_REG', 3)->nullable();
            $table->string('DOC_INCO01', 100)->nullable();
            $table->string('DOC_INCO02', 100)->nullable();
            $table->string('DOC_INCO03', 100)->nullable();
            $table->string('DOC_INCO31', 30)->nullable();
            $table->string('DOC_INCO32', 30)->nullable();
            $table->string('DOC_INCO21', 20)->nullable();
            $table->string('DOC_INCO22', 20)->nullable();
            $table->string('DOC_INCO23', 20)->nullable();
            $table->string('DOC_INCO24', 20)->nullable();
            $table->string('DOC_INCO25', 20)->nullable();
            $table->float('DOC_POIDSB', 53, 0)->nullable();
            $table->float('DOC_POIDSN', 53, 0)->nullable();
            $table->float('DOC_NCOLIS', 53, 0)->nullable();
            $table->float('DOC_VOLUME', 53, 0)->nullable();
            $table->decimal('DOC_REMLIG', 20, 4)->nullable();
            $table->decimal('DOC_BRUT', 20, 4)->nullable();
            $table->decimal('DOC_REMCLI', 20, 4)->nullable();
            $table->decimal('DOC_TXRFAC', 8, 3)->nullable();
            $table->decimal('DOC_REMFAC', 20, 4)->nullable();
            $table->string('DOC_CPORT', 3)->nullable();
            $table->string('DOC_PPORT', 3)->nullable();
            $table->decimal('DOC_PORT', 20, 4)->nullable();
            $table->string('DOC_CFRAIS', 3)->nullable();
            $table->string('DOC_PFRAIS', 3)->nullable();
            $table->decimal('DOC_FRAIS', 20, 4)->nullable();
            $table->string('DOC_CSUPPL', 3)->nullable();
            $table->string('DOC_PSUPPL', 3)->nullable();
            $table->decimal('DOC_SUPPL', 20, 4)->nullable();
            $table->float('DOC_CFRAPP', 53, 0)->nullable();
            $table->decimal('DOC_TVA_T1', 8, 3)->nullable();
            $table->string('DOC_TVA_C1', 1)->nullable();
            $table->decimal('DOC_TVA_B1', 20, 4)->nullable();
            $table->decimal('DOC_TVA_T2', 8, 3)->nullable();
            $table->string('DOC_TVA_C2', 1)->nullable();
            $table->decimal('DOC_TVA_B2', 20, 4)->nullable();
            $table->decimal('DOC_TVA_T3', 8, 3)->nullable();
            $table->string('DOC_TVA_C3', 1)->nullable();
            $table->decimal('DOC_TVA_B3', 20, 4)->nullable();
            $table->decimal('DOC_TVA_T4', 8, 3)->nullable();
            $table->string('DOC_TVA_C4', 1)->nullable();
            $table->decimal('DOC_TVA_B4', 20, 4)->nullable();
            $table->decimal('DOC_TVA_T5', 8, 3)->nullable();
            $table->string('DOC_TVA_C5', 1)->nullable();
            $table->decimal('DOC_TVA_B5', 20, 4)->nullable();
            $table->decimal('DOC_TPF_T1', 8, 3)->nullable();
            $table->string('DOC_TPF_C1', 1)->nullable();
            $table->decimal('DOC_TPF_B1', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X1', 8, 3)->nullable();
            $table->string('DOC_TPF_E1', 15)->nullable();
            $table->decimal('DOC_TPF_T2', 8, 3)->nullable();
            $table->string('DOC_TPF_C2', 1)->nullable();
            $table->decimal('DOC_TPF_B2', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X2', 8, 3)->nullable();
            $table->string('DOC_TPF_E2', 15)->nullable();
            $table->decimal('DOC_TPF_T3', 8, 3)->nullable();
            $table->string('DOC_TPF_C3', 1)->nullable();
            $table->decimal('DOC_TPF_B3', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X3', 8, 3)->nullable();
            $table->string('DOC_TPF_E3', 15)->nullable();
            $table->decimal('DOC_TPF_T4', 8, 3)->nullable();
            $table->string('DOC_TPF_C4', 1)->nullable();
            $table->decimal('DOC_TPF_B4', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X4', 8, 3)->nullable();
            $table->string('DOC_TPF_E4', 15)->nullable();
            $table->decimal('DOC_TPF_T5', 8, 3)->nullable();
            $table->string('DOC_TPF_C5', 1)->nullable();
            $table->decimal('DOC_TPF_B5', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X5', 8, 3)->nullable();
            $table->string('DOC_TPF_E5', 15)->nullable();
            $table->decimal('DOC_TPF_T6', 8, 3)->nullable();
            $table->string('DOC_TPF_C6', 1)->nullable();
            $table->decimal('DOC_TPF_B6', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X6', 8, 3)->nullable();
            $table->string('DOC_TPF_E6', 15)->nullable();
            $table->decimal('DOC_TPF_T7', 8, 3)->nullable();
            $table->string('DOC_TPF_C7', 1)->nullable();
            $table->decimal('DOC_TPF_B7', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X7', 8, 3)->nullable();
            $table->string('DOC_TPF_E7', 15)->nullable();
            $table->decimal('DOC_TPF_T8', 8, 3)->nullable();
            $table->string('DOC_TPF_C8', 1)->nullable();
            $table->decimal('DOC_TPF_B8', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X8', 8, 3)->nullable();
            $table->string('DOC_TPF_E8', 15)->nullable();
            $table->decimal('DOC_TPF_T9', 8, 3)->nullable();
            $table->string('DOC_TPF_C9', 1)->nullable();
            $table->decimal('DOC_TPF_B9', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X9', 8, 3)->nullable();
            $table->string('DOC_TPF_E9', 15)->nullable();
            $table->decimal('DOC_TPF_T10', 8, 3)->nullable();
            $table->string('DOC_TPF_C10', 1)->nullable();
            $table->decimal('DOC_TPF_B10', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X10', 8, 3)->nullable();
            $table->string('DOC_TPF_E10', 15)->nullable();
            $table->decimal('DOC_TPF_T11', 8, 3)->nullable();
            $table->string('DOC_TPF_C11', 1)->nullable();
            $table->decimal('DOC_TPF_B11', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X11', 8, 3)->nullable();
            $table->string('DOC_TPF_E11', 15)->nullable();
            $table->decimal('DOC_TPF_T12', 8, 3)->nullable();
            $table->string('DOC_TPF_C12', 1)->nullable();
            $table->decimal('DOC_TPF_B12', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X12', 8, 3)->nullable();
            $table->string('DOC_TPF_E12', 15)->nullable();
            $table->decimal('DOC_TPF_T13', 8, 3)->nullable();
            $table->string('DOC_TPF_C13', 1)->nullable();
            $table->decimal('DOC_TPF_B13', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X13', 8, 3)->nullable();
            $table->string('DOC_TPF_E13', 15)->nullable();
            $table->decimal('DOC_TPF_T14', 8, 3)->nullable();
            $table->string('DOC_TPF_C14', 1)->nullable();
            $table->decimal('DOC_TPF_B14', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X14', 8, 3)->nullable();
            $table->string('DOC_TPF_E14', 15)->nullable();
            $table->decimal('DOC_TPF_T15', 8, 3)->nullable();
            $table->string('DOC_TPF_C15', 1)->nullable();
            $table->decimal('DOC_TPF_B15', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X15', 8, 3)->nullable();
            $table->string('DOC_TPF_E15', 15)->nullable();
            $table->decimal('DOC_TPF_T16', 8, 3)->nullable();
            $table->string('DOC_TPF_C16', 1)->nullable();
            $table->decimal('DOC_TPF_B16', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X16', 8, 3)->nullable();
            $table->string('DOC_TPF_E16', 15)->nullable();
            $table->decimal('DOC_TPF_T17', 8, 3)->nullable();
            $table->string('DOC_TPF_C17', 1)->nullable();
            $table->decimal('DOC_TPF_B17', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X17', 8, 3)->nullable();
            $table->string('DOC_TPF_E17', 15)->nullable();
            $table->decimal('DOC_TPF_T18', 8, 3)->nullable();
            $table->string('DOC_TPF_C18', 1)->nullable();
            $table->decimal('DOC_TPF_B18', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X18', 8, 3)->nullable();
            $table->string('DOC_TPF_E18', 15)->nullable();
            $table->decimal('DOC_TPF_T19', 8, 3)->nullable();
            $table->string('DOC_TPF_C19', 1)->nullable();
            $table->decimal('DOC_TPF_B19', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X19', 8, 3)->nullable();
            $table->string('DOC_TPF_E19', 15)->nullable();
            $table->decimal('DOC_TPF_T20', 8, 3)->nullable();
            $table->string('DOC_TPF_C20', 1)->nullable();
            $table->decimal('DOC_TPF_B20', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X20', 8, 3)->nullable();
            $table->string('DOC_TPF_E20', 15)->nullable();
            $table->decimal('DOC_TPF_T21', 8, 3)->nullable();
            $table->string('DOC_TPF_C21', 1)->nullable();
            $table->decimal('DOC_TPF_B21', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X21', 8, 3)->nullable();
            $table->string('DOC_TPF_E21', 15)->nullable();
            $table->decimal('DOC_TPF_T22', 8, 3)->nullable();
            $table->string('DOC_TPF_C22', 1)->nullable();
            $table->decimal('DOC_TPF_B22', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X22', 8, 3)->nullable();
            $table->string('DOC_TPF_E22', 15)->nullable();
            $table->decimal('DOC_TPF_T23', 8, 3)->nullable();
            $table->string('DOC_TPF_C23', 1)->nullable();
            $table->decimal('DOC_TPF_B23', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X23', 8, 3)->nullable();
            $table->string('DOC_TPF_E23', 15)->nullable();
            $table->decimal('DOC_TPF_T24', 8, 3)->nullable();
            $table->string('DOC_TPF_C24', 1)->nullable();
            $table->decimal('DOC_TPF_B24', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X24', 8, 3)->nullable();
            $table->string('DOC_TPF_E24', 15)->nullable();
            $table->decimal('DOC_TPF_T25', 8, 3)->nullable();
            $table->string('DOC_TPF_C25', 1)->nullable();
            $table->decimal('DOC_TPF_B25', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X25', 8, 3)->nullable();
            $table->string('DOC_TPF_E25', 15)->nullable();
            $table->decimal('DOC_TPF_T26', 8, 3)->nullable();
            $table->string('DOC_TPF_C26', 1)->nullable();
            $table->decimal('DOC_TPF_B26', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X26', 8, 3)->nullable();
            $table->string('DOC_TPF_E26', 15)->nullable();
            $table->decimal('DOC_TPF_T27', 8, 3)->nullable();
            $table->string('DOC_TPF_C27', 1)->nullable();
            $table->decimal('DOC_TPF_B27', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X27', 8, 3)->nullable();
            $table->string('DOC_TPF_E27', 15)->nullable();
            $table->decimal('DOC_TPF_T28', 8, 3)->nullable();
            $table->string('DOC_TPF_C28', 1)->nullable();
            $table->decimal('DOC_TPF_B28', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X28', 8, 3)->nullable();
            $table->string('DOC_TPF_E28', 15)->nullable();
            $table->decimal('DOC_TPF_T29', 8, 3)->nullable();
            $table->string('DOC_TPF_C29', 1)->nullable();
            $table->decimal('DOC_TPF_B29', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X29', 8, 3)->nullable();
            $table->string('DOC_TPF_E29', 15)->nullable();
            $table->decimal('DOC_TPF_T30', 8, 3)->nullable();
            $table->string('DOC_TPF_C30', 1)->nullable();
            $table->decimal('DOC_TPF_B30', 20, 4)->nullable();
            $table->decimal('DOC_TPF_X30', 8, 3)->nullable();
            $table->string('DOC_TPF_E30', 15)->nullable();
            $table->decimal('DOC_MT_HT', 20, 4)->nullable();
            $table->decimal('DOC_MT_TVA', 20, 4)->nullable();
            $table->decimal('DOC_MT_TPF', 20, 4)->nullable();
            $table->decimal('DOC_TVATPF', 20, 4)->nullable();
            $table->decimal('DOC_MT_TTC', 20, 4)->nullable();
            $table->decimal('DOC_ACPTE', 20, 4)->nullable();
            $table->boolean('DOC_ACPANT')->nullable();
            $table->decimal('DOC_TX_ESC', 8, 3)->nullable();
            $table->decimal('DOC_MT_ESC', 20, 4)->nullable();
            $table->decimal('DOC_TX_RG', 8, 3)->nullable();
            $table->decimal('DOC_MT_RG', 20, 4)->nullable();
            $table->decimal('DOC_MT_NET', 20, 4)->nullable();
            $table->decimal('DOC_COUT', 20, 4)->nullable();
            $table->decimal('DOC_MARGE', 20, 4)->nullable();
            $table->decimal('DOC_PRVECH', 20, 4)->nullable();
            $table->string('DOC_TC_DA', 3)->nullable();
            $table->string('DOC_TC_EMP', 35)->nullable();
            $table->dateTime('DOC_DDTASS')->nullable();
            $table->string('DOC_ETAASS', 15)->nullable();
            $table->boolean('DOC_ABRQ')->nullable();
            $table->dateTime('DOC_ABRQLE')->nullable();
            $table->string('DOC_ABRQPR', 20)->nullable();
            $table->string('DOC_MOABRQ', 15)->nullable();
            $table->decimal('DOC_ECHRES', 20, 4)->nullable();
            $table->string('DOC_TRTCRE', 3)->nullable();
            $table->dateTime('DOC_DTCRE')->nullable();
            $table->string('DOC_USRCRE', 20)->nullable();
            $table->dateTime('DOC_DTMAJ')->nullable();
            $table->string('DOC_USRMAJ', 20)->nullable();
            $table->integer('DOC_NUMMAJ')->nullable();
            $table->string('DOC_CLEINA', 300)->nullable();
            $table->string('XXX_CLI', 20)->nullable();
            $table->dateTime('XXX_ECH')->nullable();
            $table->string('XXX_ETAT', 20)->nullable();
            $table->float('XXX_PMAMT', 53, 0)->nullable();
            $table->float('XXX_PONMAR', 53, 0)->nullable();
            $table->string('XXX_REU', 20)->nullable();
            $table->string('XXX_TOUR', 60)->nullable();

            $table->index(['DEP_CODE', 'DOC_TYPE', 'DOC_STYPE', 'DOC_ETAT'], 'adc_kdep');
            $table->unique(['DOC_TYPE', 'DEV_CODE', 'DOC_MT_TTC', 'DOC_DATE', 'DOC_PIECE'], 'adc_kmtttc');
            $table->unique(['DOC_TYPE', 'DOC_PIECE', 'DOC_DATE'], 'adc_kpiece');
            $table->unique(['DOC_TYPE', 'DOC_STYPE', 'DOC_DATE', 'DOC_PIECE'], 'adc_ksdate');
            $table->index(['DOC_TYPE', 'DOC_STYPE', 'PCF_CODE', 'DOC_DATE'], 'adc_kspcf');
            $table->unique(['DOC_TYPE', 'DOC_DATE', 'DOC_PIECE'], 'adc_ktdate');
            $table->index(['DOC_TDEPOT', 'DOC_ETAT'], 'adc_ktdep');
            $table->index(['PCF_CODE', 'DOC_DATE'], 'adc_ktiers');
            $table->index(['DOC_TYPE', 'PCF_CODE', 'DOC_DATE'], 'adc_ktpcf');
            $table->index(['DOC_TYPE', 'PCF_PAYEUR', 'DOC_NUMERO', 'DOC_STYPE', 'DOC_DATE'], 'adc_ktpnsd');
            $table->index(['DOC_TYPE', 'PRJ_CODE'], 'adc_ktprj');
            $table->index(['DOC_TYPE', 'REP_CODE', 'DEP_CODE', 'DOC_STYPE', 'DOC_DATE'], 'adc_ktrdsd');
            $table->index(['DOC_TYPE', 'DOC_STYPE'], 'adc_kts');
            $table->index(['DOC_TYPE', 'DOC_STYPE', 'DEP_CODE', 'DOC_DATE'], 'adc_ktsdd');
            $table->primary(['DOC_NUMERO'], 'adc_pnum');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('ARC_DOCUMENTS');
    }
};
